### ISSUE TITLE
Android API  23,25,26,27  can't read  /data/data/<appid>/files/   , on simulator

### ISSUE THREAD

**Issue by sisong** [sisong/UnityAndroidHotUpdate#21]
same:  can't read /data/user/0/```<appid>```/files/    
(API 24,28 ok)

**Comment by sisong** [comment]
It's is probably a permission error only on the simulator；    
test on an Android8.0(API 26) phone device is ok;

**Comment by sisong** [comment]
test on another Android 7.1.1(API 25) with play simulator is ok;   
test on another Android 8.0(API 26) with play simulator is ok;   
test on another Android 8.1(API 27) with play simulator is ok;      
add a new test by code on Android API 23  with simulator is ok;

**Comment by sisong** [comment]
Probably is simulator bug

**Comment by sisong** [comment]
on Android API 23 with a phone device is ok;

**Comment by shishu123cn** [comment]
Cannot read on Android API 28
