### ISSUE TITLE
testHotUpdate 测试报错

### ISSUE THREAD

**Issue by linkongchen** [sisong/UnityAndroidHotUpdate#48]
private static void testHotUpdate(Context app,
                                      String baseApk,String baseSoDir,
                                      String hotApk,String hotSoDir,
                                      String newApk,String newSoDir){
        if (pathIsExists(newApk)||(pathIsExists(newSoDir))) return;
        String testDir=app.getExternalFilesDir("").getAbsolutePath()+"/testHotUpdate";
        //default: testDir=="/sdcard/Android/data/<your-app-id>/files/testHotUpdate";
        //NOTE: put the files you need test into the testDir directory
        String testPatFile=testDir+"/new.pat"; //test pat file
        if (!pathIsExists(testPatFile)) return;
        Log.w(kLogTag, "testHotUpdate() with "+testPatFile);
        mapPathLoadLib(hotSoDir,kHotUnityLib); //for native function: virtualApkPatch()

        String testBase=testDir+"/base.apk";
        if (pathIsExists(testBase)) {
            baseApk  = testBase;
            baseSoDir= testBase + "_lib";
        }
        String testHot=testDir+"/update.apk";
        if (pathIsExists(testBase)||pathIsExists(testHot)) {
            hotApk  = testHot;
            hotSoDir= testHot + "_lib";
        }
        int  ret=virtualApkPatch(baseApk,baseSoDir,hotApk,hotSoDir,
                 newApk,newSoDir,testPatFile,3);
        Log.w(kLogTag, "virtualApkPatch() result " +String.valueOf(ret));
        if ((ret==0) && removeFile(testPatFile)){ //update ok
            Log.w(kLogTag, "testHotUpdate() ok");
        }else{
            Log.w(kLogTag, "testHotUpdate() ERROR, exitApp");
            exitApp(ret);
        }
    }

看了代码，有一个test方法，拿一个空项目按照代码设置文件夹和new.pat

执行结果报错
2020-11-05 19:25:35.244 21034-21060/com.rsg.wdwt E/Unity: Inflate Error: invalid stored block lengths (file zip crc32 : 19676369) (result: fffffffd)
     
    (Filename:  Line: 212)

**Comment by linkongchen** [comment]
已经解决，参考这个流程https://github.com/sisong/UnityAndroidHotUpdate/releases/tag/v1.0.0-beta

**Comment by sisong** [comment]
我测试的时候还是用testHotUpdate比较多；     
你可以用Unity导出`Android Studio`项目，调试看看具体在什么位置发生了什么错误

**Comment by linkongchen** [comment]
你好，刚看见邮件，这个问题已经通过使用Unity导出Android Studio项目解决，多谢~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "housisong"<notifications@github.com&gt;; 
发送时间: 2020年11月8日(星期天) 下午4:29
收件人: "sisong/UnityAndroidHotUpdate"<UnityAndroidHotUpdate@noreply.github.com&gt;; 
抄送: "素月临空"<282233737@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sisong/UnityAndroidHotUpdate] testHotUpdate 测试报错 (#48)





 
我测试的时候还是用testHotUpdate比较多；
 你可以用Unity导出Android Studio项目，调试看看具体在什么位置发生了什么错误
