### ISSUE TITLE
无感知更新so?

### ISSUE THREAD

**Issue by RPG3D** [sisong/UnityAndroidHotUpdate#49]
支持更新libunity.so?
这个更新so是否具有广泛性?跟unity无关的一些ndk编译的动态库也可以更新吗?(程序逻辑来保证更新结束加载so) 
跟商店(国内国外)规则会不会有冲突?

**Comment by sisong** [comment]
“这个更新so是否具有广泛性??跟unity无关的一些ndk编译的动态库也可以更新吗?”      
可以   
   
“跟商店(国内国外)规则会不会有冲突?”   
没有大的冲突
