### ISSUE TITLE
Failed to load Il2CPP

### ISSUE THREAD

**Issue by wannayi** [sisong/UnityAndroidHotUpdate#50]
将libil2cpp.so  放入update.apk_lib中, 重启后提示  Error : Failed to load Il2CPP.

**Comment by sisong** [comment]
是你的app还是本仓库demo的app？     
是否还有其他.so文件也发生了变化？     
加载失败还有其他更多日志信息吗？ 是否是路径问题？ ...

**Comment by sisong** [comment]
是你的app还是本仓库demo的app？     
是否还有其他.so文件也发生了变化？     
加载失败还有其他更多日志信息吗？ 是否是路径问题？ ...

**Comment by wannayi** [comment]
![image](https://user-images.githubusercontent.com/34264399/111432752-6063be80-8738-11eb-9be7-fbec6bc05fab.png)
这是日志
Unity空项目, 只有一个脚本.  Unity2019.4.13f1

**Comment by wannayi** [comment]
就改了一行代码,  理论应该只有libIl2Cpp.so  变动了

**Comment by wannayi** [comment]
试了下, 的确是路径问题,   直接放update.apk_lib里了,  应该放在 update,apk_lib/abi(arm64-v8a)/

**Comment by wannayi** [comment]
使用temp_new.pat 出现Crash
![image](https://user-images.githubusercontent.com/34264399/111570409-c2c3ca00-87df-11eb-870b-10da673fb8fb.png)

**Comment by wannayi** [comment]
只新增了一个C#脚本

**Comment by wannayi** [comment]
只新增了一个C#脚本和一个场景
