### ISSUE TITLE
是否支持多补丁更新？

### ISSUE THREAD

**Issue by Zuile** [sisong/UnityAndroidHotUpdate#51]
请问如果有多个补丁包的话，这种情况该如何处理，我尝试了用不同的补丁包连续调用两次apkPatch，第二次调用的时候返回的不是0，是否有方法能一次更新完多个补丁包，而不用重启多次，或者能在本地将多个补丁包合成一个，再调用apkPatch

**Comment by sisong** [comment]
推荐的方式是创建多个旧版本到最新版本的补丁，这样对所有版本的用户都只用下载一个补丁就可以了。（不用保留历史补丁）  
      
   
> “连续调用两次apkPatch，第二次调用的时候返回的不是0”     

不是原理上的问题，而是实现时打补丁分成了2个阶段，先patch出新文件到临时目录，只有重启后再merge回去覆盖掉以前的旧文件。这样做是为了安全，避免直接“热”替换失败，比如.so正在执行，某些文件正在访问？     
如果你认为没有问题，可以安全替换；那可以在第一次patch成功后，继续调用mergeNewUpdate()完成替换；然后打第二个补丁。 或者就需要修改逻辑来支持连续打补丁。
