### ISSUE TITLE
热更不生效

### ISSUE THREAD

**Issue by SiMaLaoShi** [sisong/UnityAndroidHotUpdate#53]

**Comment by SiMaLaoShi** [comment]
Unity2020.4.36的版本

**Comment by sisong** [comment]
为什么又关闭了，问题解决了吗

**Comment by SiMaLaoShi** [comment]
解决了，姿势不对，我没用你的包名，但是热更好像不生效

**Comment by SiMaLaoShi** [comment]
![image](https://user-images.githubusercontent.com/28924681/200541706-9a25479b-666e-48c9-b783-768f9901e766.png)
![image](https://user-images.githubusercontent.com/28924681/200541723-80d36194-44ea-4670-85a7-1495df1bdce2.png)
我再研究研究

**Comment by SiMaLaoShi** [comment]
如何看热更是否生效啊，Native层有没有想过的日志

**Comment by SiMaLaoShi** [comment]
![image](https://user-images.githubusercontent.com/28924681/200542202-01006083-7841-4815-83d1-8e0758d2f534.png)
看想过的日志都执行到了

**Comment by sisong** [comment]
建议开发步骤：   
* 手动放 相关目录测试： 注意代码 `boolean isRunHot=...`  手工将新版本的so和apk文件放置到约定路径。如果isRunHot为真，将执行新版本   
* 用testHotUpdate函数测试更新过程： 放入old.apk和升级补丁文件，调用patch函数看能否得到 上一个步骤手工操作的结果。
* 真实完整的测试升级过程。

**Comment by SiMaLaoShi** [comment]
是步骤一的操作没错，看运行日志isRunHot是true，但是确实不生效
![image](https://user-images.githubusercontent.com/28924681/201251352-eabc15fa-71ef-4c41-91ff-cc9f285d7842.png)
![image](https://user-images.githubusercontent.com/28924681/201251378-1cfb9935-0d1b-4b02-9d5f-b1eb8eac10eb.png)

**Comment by sisong** [comment]
这种情况，怀疑是旧版本已经在此之前已经加载。 看看插入拦截代码的位置附近的代码。   也可以在apk中加入日志打印自己的版本号来看看加载情况。

**Comment by SiMaLaoShi** [comment]
插入的位置是根据文档来的，我再测试一下版本号
![image](https://user-images.githubusercontent.com/28924681/201253974-a6a72fe3-f357-4186-b6b7-303467a65052.png)

**Comment by sisong** [comment]
应该是 libmain.so 的问题：  你应该没有用项目带的 fix_unity_jar 命令行处理过jar包，所以不支持它的热更。

**Comment by SiMaLaoShi** [comment]
确实没有，我看文档里说小版本才需要就没处理，我看没有编译好的吗

**Comment by SiMaLaoShi** [comment]
![image](https://user-images.githubusercontent.com/28924681/201450725-deb8b136-06a9-469f-afc7-edf9f995a8f2.png)
子模块里面的好像变更有点大

**Comment by SiMaLaoShi** [comment]
我感觉这个fix应该写个ReadMe

**Comment by SiMaLaoShi** [comment]
处理也不行，这个jar怎么看是修改了哪里，我反编译看一下
![image](https://user-images.githubusercontent.com/28924681/201451140-b9336509-511a-482d-829a-c5c2a2b9085f.png)

**Comment by sisong** [comment]
我记得文档有写过说明教程。  
你先把这个main.so移除，测试通过再说。 热更main.so操作比较复杂，也有风险(Java层和so层版本不配套)。

**Comment by SiMaLaoShi** [comment]
好的感谢，是移除热更的main.so吧，我这移除了热更的main.so，只保留了i2cpp.so会Crash
![image](https://user-images.githubusercontent.com/28924681/201451457-fe1cf586-94b5-4ce4-895d-a11b88878895.png)
libunity.so是否要保留
我后面追踪一下符号表，再次感谢

**Comment by SiMaLaoShi** [comment]
![image](https://user-images.githubusercontent.com/28924681/201562478-8d1b661f-fe43-4328-b29a-d7606ac68000.png)
只保留i2cpp的话提示这个

**Comment by SiMaLaoShi** [comment]
还是更新不生效
11-14 10:29:36.586 5731-5731/com.DefaultCompany.Uni2020 E/HotUnity: hotApk:/data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk
11-14 10:29:36.586 5731-5731/com.DefaultCompany.Uni2020 E/HotUnity: hotSo:/data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib
11-14 10:29:36.586 5731-5731/com.DefaultCompany.Uni2020 E/HotUnity: runByHotApk
11-14 10:29:36.586 5731-5731/com.DefaultCompany.Uni2020 W/HotUnity: java map_path() not found /data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib/libmain.so
11-14 10:29:36.592 5731-5731/com.DefaultCompany.Uni2020 W/HotUnity: java map_path() not found /data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib/libunity.so
11-14 10:29:36.639 5731-5731/com.DefaultCompany.Uni2020 W/HotUnity: java map_path() not found /data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib/libhotunity.so
11-14 10:29:36.642 5731-5731/com.DefaultCompany.Uni2020 E/HotUnity: baseApk{/data/app/com.DefaultCompany.Uni2020-1/base.apk}
    baseSoDir{/data/app/com.DefaultCompany.Uni2020-1/lib/arm64}
    hotApk{/data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk}
    hotSoDir{/data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib}
11-14 10:29:36.642 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: hook_unity_doHook() from: /data/app/com.DefaultCompany.Uni2020-1/base.apk  /data/app/com.DefaultCompany.Uni2020-1/lib/arm64
11-14 10:29:36.643 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: hook_unity_doHook() to: /data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk  /data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib
11-14 10:29:36.643 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: hook_lib() to hook libmain.so
11-14 10:29:36.659 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: hook_lib() to hook libunity.so
11-14 10:29:36.681 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x1a7d9520 /data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib/libil2cpp.so
11-14 10:29:36.681 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: hook_lib() to hook /data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib/libil2cpp.so
11-14 10:29:36.694 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x1a7d2290 /data/app/com.DefaultCompany.Uni2020-1/lib/arm64/libunity.so
11-14 10:29:36.695 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: hook_lib() to hook /data/app/com.DefaultCompany.Uni2020-1/lib/arm64/libunity.so
11-14 10:29:36.698 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x1a7d9520 /data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib/libil2cpp.so
11-14 10:29:36.698 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: hook_lib() to hook /data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib/libil2cpp.so
11-14 10:29:36.703 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x00000000 /data/app/com.DefaultCompany.Uni2020-1/lib/arm64/libMGD.so
11-14 10:29:36.703 5731-5731/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x00000000 libMGD.so
11-14 10:29:36.837 5731-5749/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x1a7cfc60 libc.so
11-14 10:29:36.910 5731-5749/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x1a7d35a8 libandroid.so
11-14 10:29:36.966 5731-5749/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x1a7d9520 /data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib/libil2cpp.so
11-14 10:29:36.966 5731-5749/com.DefaultCompany.Uni2020 I/HotUnity: hook_lib() to hook /data/user/0/com.DefaultCompany.Uni2020/files/HotUpdate/update.apk_lib/libil2cpp.so
11-14 10:29:37.164 5731-5749/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x00000000 libvulkan.so
11-14 10:29:37.227 5731-5749/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x00000000 libMGD.so
11-14 10:29:37.228 5731-5749/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x1a7da838 libGLESv2.so
11-14 10:29:37.250 5731-5749/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x1a7d5bd8 libEGL.so
11-14 10:29:37.253 5731-5749/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x1a7d35a8 libandroid.so
11-14 10:29:37.305 5731-5749/com.DefaultCompany.Uni2020 I/HotUnity: dlopen() result 0x1a7dce68 libOpenSLES.so
