### ISSUE TITLE
手工热更新测试错误

### ISSUE THREAD

**Issue by dawn25618** [sisong/UnityAndroidHotUpdate#54]
手工热更新测试错误，希望大佬指点我一下。大佬能加一下Q吗？2229713767

执行 doHot(baseApk,baseSoDir,hotApk,hotSoDir);就报错了，可是so库都是在release中下载的，然后直接导入的jniLibs目录文件下

java.lang.UnsatisfiedLinkError: No implementation found for void com.unity3d.update.HotUnity.doHot(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_com_unity3d_update_HotUnity_doHot and Java_com_unity3d_update_HotUnity_doHot__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)

**Comment by sisong** [comment]
Java代码的类路径和名称都不能改，否则找不到so中的函数
